# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hero < Formula
  desc "Persistent project memory and delivery workflows for AI engineering agents"
  homepage "https://heroengine.ai"
  version "0.34.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.34.0/hero_0.34.0_darwin_amd64.tar.gz"
      sha256 "4cca2ea075b0f99e83532827abe0e866801b7e0a35f6f779ec031899ffe1a475"

      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.34.0/hero_0.34.0_darwin_arm64.tar.gz"
      sha256 "780f2d4aa32302200c77b21cfb7756cc6fbeb6056ea3e55546ebf5e8ed5e7718"

      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.34.0/hero_0.34.0_linux_amd64.tar.gz"
      sha256 "598c8511d63b1fe340ebfeda1ca06c135a7aa760d722bd31c537be3ad278ed68"
      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.34.0/hero_0.34.0_linux_arm64.tar.gz"
      sha256 "851d5931738f3af806d6f617f87d0ec48b0c7191f18798769dee943243bc6f31"
      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  test do
    system "#{bin}/hero", "--version"
  end
end
