# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hero < Formula
  desc "Spec-driven AI engineering workflow"
  homepage "https://hero-engine.dev"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.18.0/hero_0.18.0_darwin_amd64.tar.gz"
      sha256 "055c184385ce0510f8653dcc6118fb44b048305bafbecb566554a825a559db85"

      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.18.0/hero_0.18.0_darwin_arm64.tar.gz"
      sha256 "fdbb591dd538b4ed62e477addda5a5f14ea1bd69d2115c3cbaf845587e912dc8"

      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.18.0/hero_0.18.0_linux_amd64.tar.gz"
      sha256 "52a45af4a2ec4b1271fc15a74b4d5a9028c7b62ec795aac9913ce481536af9a4"
      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hero-engine/hero-releases/releases/download/v0.18.0/hero_0.18.0_linux_arm64.tar.gz"
      sha256 "c9ba39a0920af5765f755efcf317791ed59b343236bf484034fc08d43d589901"
      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  test do
    system "#{bin}/hero", "--version"
  end
end
